name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and build 
        run: | 
          npm ci 
          npm run build 

      - name: Publish site
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: _site
        
